// frontend/source/comps/CenterPane.tsx
import type { Entry } from "../types/entry"
import { PanelEntry } from "./PanelEntry"

type CenterPaneProps = {
    centerEntries: Entry[]
    cursor?: number
    marked?: Set<string>
}

export function CenterPane({ centerEntries, cursor = -1, marked }: CenterPaneProps) {
    return (
        <section style={styles.container}>
            <PanelEntry entries={centerEntries} variant="center" cursor={cursor} marked={marked} />
        </section>
    )
}

const styles = {
    container: {
        minWidth: "0",
        minHeight: "0",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        borderRight: "1px solid var(--border)",
        borderLeft: "1px solid var(--border)",
    },
}

// frontend/source/components/CenterPane.svelte
<script lang="ts">
    import type { Entry } from "../types";
    import PanelEntry from "./PanelEntry.svelte";

    let { centerEntries, cursor = -1, marked }: { centerEntries: Entry[]; cursor?: number; marked?: Set<string> } = $props();
</script>


<section class="center-pane">
    <PanelEntry entries={centerEntries} variant="center" {cursor} {marked} />
</section>

<style>
    .center-pane {
        min-width: 0;
        min-height: 0;
        overflow: hidden;
        display: flex;
        flex-direction: column;
        border-right: 1px solid var(--border);
        border-left: 1px solid var(--border);
    }
</style>
