// frontend/source/comps/ParentPane.tsx
import type { Entry } from "../types/entry"
import { PanelEntry } from "./PanelEntry"

type ParentPaneProps = {
    parentEntries: Entry[]
    highlightPath?: string
}

export function ParentPane({ parentEntries, highlightPath }: ParentPaneProps) {
    return (
        <section style={styles.container}>
            <PanelEntry entries={parentEntries} variant="parent" highlightPath={highlightPath} />
        </section>
    )
}

const styles = {
    container: {
        minWidth: "0",
        minHeight: "0",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
    },
}

// frontend/source/components/ParentPane.svelte
<script lang="ts">
    import type { Entry } from "../types";
    import PanelEntry from "./PanelEntry.svelte";

    let { parentEntries, highlightPath }: { parentEntries: Entry[]; highlightPath?: string } = $props();
</script>

<section class="parent-pane">
    <PanelEntry entries={parentEntries} variant="parent" {highlightPath} />
</section>

<style>
    .parent-pane {
        min-width: 0;
        min-height: 0;
        overflow: hidden;
        display: flex;
        flex-direction: column;
    }
</style>
