// frontend/source/comps/PathBar.tsx
import { useAppState } from "../state/appState"

export function PathBar() {
    const { cwd, loading } = useAppState()
    return (
        <div style={styles.container}>
            <span>{cwd || (loading ? "…" : "")}</span>
        </div>
    )
}

const styles = {
    container: {
        padding: "0.35rem 0.75rem",
        background: "var(--panel)",
        borderTop: "1px solid var(--border)",
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    },
}

// frontend/source/components/PathBar.svelte
<script lang="ts">
    import { appState } from "../states/state.svelte";
</script>

<div class="path-bar">
    <span>{appState.cwd || (appState.loading ? "…" : "")}</span>
</div>

<style>

.path-bar {
  padding: 0.35rem 0.75rem;
  background: var(--panel);
  border-bottom: 1px solid var(--border);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

</style>
