// frontend/source/comps/TriPanel.tsx
import { useAppState } from "../state/appState"
import { CenterPane } from "./CenterPane"
import { ParentPane } from "./ParentPane"
import { PreviewPane } from "./PreviewPane"

export function TriPanel() {
    const { parentEntries, entries, rightEntries, cwd, cursor, marked } = useAppState()

    return (
        <div style={styles.container}>
            <ParentPane parentEntries={parentEntries} highlightPath={cwd} />
            <CenterPane centerEntries={entries} cursor={cursor} marked={marked} />
            <PreviewPane previewEntries={rightEntries} />
        </div>
    )
}


const styles = {
    container: {
    display: "grid",
    gridTemplateColumns: "2fr 4fr 3fr",
    minHeight: 0,
  },
}

// frontend/source/components/TriPanel.svelte
<script lang="ts">
    import type { Entry } from "../types";
    import PreviewPane from "./PreviewPane.svelte";
    import ParentPane from "./ParentPane.svelte";
    import CenterPane from "./CenterPane.svelte";

    import { appState } from "../states/state.svelte";

    let parentEntries: Entry[] = $derived(appState.parentEntries);
    let centerEntries: Entry[] = $derived(appState.entries);
    let previewEntries: Entry[] = $derived(appState.rightEntries);
    let highlightPath: string = $derived(appState.cwd);
    let cursor: number = $derived(appState.cursor);
    let marked: Set<string> = $derived(appState.marked);
</script>

<div class="tri-panel">
    <ParentPane {parentEntries} {highlightPath} />
    <CenterPane {centerEntries} {cursor} {marked} />
    <PreviewPane {previewEntries} />
</div>

<style>
    .tri-panel {
        display: grid;
        grid-template-columns: 2fr 4fr 3fr;
        min-height: 0;
    }
</style>
